networks:
  backend-net:
    driver: 'bridge'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'cliente-db'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    volumes:
      - './mongo-data:/data/db'
    networks:
      - 'backend-net'

  mongo-express:
    image: 'mongo-express'
    container_name: 'cliente-db-gui'
    restart: 'always'
    ports:
      - "8081:8081"
    environment:
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=secret'
      - 'ME_CONFIG_MONGODB_URL=mongodb://root:secret@mongodb:27017/'
    networks:
      - 'backend-net'
    depends_on:
      - 'mongodb'